### PR TITLE
Updates to resolve open issues, and a few other minor enhancements.

### LINKED ISSUE #4: Generate better CSV filenames from file_splitter
file_splitter.py generates filenames of the format _i_.csv where _i_ is an incrementing integer starting at 0.  file_splitter ideally should preserve the original filename and append the incrementing counter to the end:  <input filename>-_i_.csv

### LINKED ISSUE #5: file_splitter.py should accept user-specified split duration parameter
Currently file_splitter splits a network-stats capture file into 5-minute chunks.  The user should be able to specify an optional duration parameter, in case they want chunks of different lengths (in minutes).  I don't see a need to over-complicate this by allowing users to specify finer-grained chunk lengths (e.g., to the second).

### PR DESCRIPTION
**Pull request by dvrx**
Input is the only required option and script needs to end gracefully when not provided.  Output dir now defaults to current directory.  Added duration arg to specify num minutes to split captures by (default is 5)

### CODE REVIEW

**Comment by dvrx** [comment]
resolves #5

**Comment by dvrx** [comment]
Output file names now match input file name + incrementing suffix.  Resolves #4.

**Review by charles-laubach — APPROVED** [review]
Looks great! Thank you very much for your improvements.

**Comment by charles-laubach** [comment]
Commit merged. Thank you for resolving issues #4 and #5!

**Pull request merged**
